
server:
  port: 0
  servlet:
    context-path: /service-bus-broker
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
api:
  title: Message Broker Service Example
  version: v1
  description: REST API Services for Message Broker
spring:
  application:
    name: Message Broker Service Example
  rabbitmq:
    listener:
      direct:
        default-requeue-rejected: false
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 2
          multiplier: 1.5
          max-interval: 5000
